### ISSUE TITLE
IMG URL parser too greedy

### ISSUE THREAD

**Issue by Fjonan** [kevinlieser/http2_push#4]
In my markup I have IMG tags that have a clear.gif as source and the real image URL as data attribute to be loaded when necessary. The http2_push plugin seems to be parsing all the image URLs from the finished markup and put them into the link header with rel=preload.

![sources](https://user-images.githubusercontent.com/21336161/37137514-5c5446c4-22a6-11e8-9e2d-e86559f6c291.jpg)
![loaded](https://user-images.githubusercontent.com/21336161/37137513-5c3a74a6-22a6-11e8-8f26-cda6056e44a7.jpg)

I suspect that the resource parser wrongfully mistakes the data-isrc= with a src= 

I think the default behavior should not include sources that would not be loaded by the browser if the markup was parsed normally.

Maybe this can be a configuration/setting for the plugin? Like "parse sources from data-http2push attributes in the markup".

**Comment by Fjonan** [comment]
I send you a pull request with the fix. Tested with the page from the screenshot above.
https://github.com/kevinlieser/http2_push/pull/6

**Comment by kevinlieser** [comment]
Merged in #6. Thanks!

**Comment by kevinlieser** [comment]
#6
