### ISSUE TITLE
Website not loading in safari

### ISSUE THREAD

**Issue by arunspt** [kevinlieser/http2_push#5]
Hello,

I've installed http2_push extension on my website, and it works well in all other browsers except safari.
In safari, the website is not loading. Please see the attached screen. Do we've any solution for this?

![bildschirmfoto 2018-05-09 um 10 46 16](https://user-images.githubusercontent.com/20816321/41821404-cd7fe34c-77fd-11e8-914b-17f215ef1119.png)

Thank you.

**Comment by kevinlieser** [comment]
Hi,

as far as I read about this problem this problem got solved by clearing the content in Safari ( https://discussions.apple.com/thread/7612610 ) or its related to a misconfigured nginx webserver.

Hope that helps.

Kevin

**Comment by arunspt** [comment]
Hello Kevin,

Thank you for the quick response. Ok, let me have a look on the possibilities you mentioned and get back to you.

Thank you,
Arun
