### ISSUE TITLE
Same source gets linked multiple times

### ISSUE THREAD

**Issue by Fjonan** [kevinlieser/http2_push#7]
I am working with "clear.gif" as a placeholder for lazy loaded images a lot and noticed, that the http2_push dumps every single occurrence into the link-header. This could blow up the header unneccesarily in some cases. This is a minor issue but I am sure can be fixed by reducing the array of found sources down to unique ones.

Here is a screenshot from my link-header-text:
![cleargif](https://user-images.githubusercontent.com/21336161/51975753-4d6fd080-2483-11e9-9d0c-b3a32fdca949.jpg)

**Comment by kevinlieser** [comment]
Fixed in 7444b4cf0b5b2048ffc445b533c41a5d812b918a. Thanks!
