### ISSUE TITLE
"link" header can get too long which results in server error 500

### ISSUE THREAD

**Issue by Fjonan** [kevinlieser/http2_push#8]
When opening a page that has a lot of different images the "link" header gets very long (see also #7 ) and on our server results in a server error 500. The last working page before the error has a "link" header string length of 8099 so I assume the "breaking point" is around 8100 and 8200 characters. I am not sure if this is a server setting or dependent on the used software, in our case it is an Apache server. It is also possible, that what Chrome dev tools show me has a max limit since the string stops with "; rel=preload; as=image" and usually the "as=image" precedes a source.

The optimal solution would be a way that finds out the max length from the system, another might be a setting that caps the max length to prevent server errors with a medium sized default value.

I did not have any entries in my error logs when this error occurs.

**Comment by kevinlieser** [comment]
I think you should be able to set the apache header size limit in the extension settings under the extension manager. Please check that.

**Comment by Fjonan** [comment]
I was not aware of this setting (sorry, I was so caught up in debugging). Setting it to 8000 fixed the problem. Thanks!
